### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by vollschauer** [Aquaeronix/aquaeronix#1]
gcc -Wall -ansi -std=gnu99 -pedantic -I /usr/include -O2 -o obj/aerocli.o -c src/aerocli.c
Assembler messages:
Fatal error: can't create obj/aerocli.o: No such file or directory
Makefile:53: recipe for target 'obj/aerocli.o' failed
make: **\* [obj/aerocli.o] Error 1

cant build it ....

**Comment by BOFH90** [comment]
same here on arch... :( 

gcc -Wall -ansi -std=gnu99 -pedantic -I /usr/include -O2 -o obj/aerocli.o -c src/aerocli.c
Assembler messages:
Fatal error: can't create obj/aerocli.o: Datei oder Verzeichnis nicht gefunden
Makefile:53: die Regel für Ziel „obj/aerocli.o“ scheiterte
make: **\* [obj/aerocli.o] Fehler 1

**Comment by barracks510** [comment]
Sorry guys. I'm waiting for my aquaero to return from a RMA. I'll see if I can reproduce the errors. Until then, you guys can try using the tempmake file to install?

**Comment by BOFH90** [comment]
With the Tempmake i get the following error:

Makefile:31: **\* missing separator.  Schluss.

It seems like "LDFLAGS" is missing in the file.

**Comment by barracks510** [comment]
Was it able to compile without the ldflags? There is a new tempmake without the ldflags.

**Comment by BOFH90** [comment]
Sry, no doesnt also build with the same error... :(

**Comment by BOFH90** [comment]
Do you already got your RMA´d Aquaero back ? ;)

**Comment by barracks510** [comment]
Got it back - burned out one of the sensors but should be able to get back into development. I'm thinking of creating a stable branch of older code for now while I check to see what to fix.

**Comment by barracks510** [comment]
Stable branch finished. Please check it out to see if it solves the problems.

**Comment by BOFH90** [comment]
It builds now and finds my Aquaero 6 Pro: 

WARNING: unsupported firmware version
----------- System -----------
Time:      2015-03-10 09:41:23
Uptime:           00d 10:13:41
CPU Temp:             32.89 °C
---- Temperature Sensors -----
Sensor  1:            27.27 °C
Sensor  2:            25.46 °C
Sensor  3:            21.85 °C
Sensor  4:            25.31 °C
Sensor  9:            27.34 °C
------------ Fans ------------
Fan  1:    474rpm @  51% 23 °C
Fan  2:      0rpm @   0% 23 °C
Fan  3:   1174rpm @   1% 23 °C
Fan  4:    455rpm @  51% 23 °C
Fan  5:      0rpm @   0% 34 °C
-------- Flow Sensors --------
Flow  1:                66 l/h
------- Liquid Levels --------
