### ISSUE TITLE
Firmware 2004 not working

### ISSUE THREAD

**Issue by BOFH90** [Aquaeronix/aquaeronix#13]
Aquacomputer released Firmware 2004 for the Aquaero.
I only get unsupported firmware now with aquaeronix.

**Comment by BOFH90** [comment]
It works just fine if changing all Lines with "2003" to "2004" :)

**Comment by BOFH90** [comment]
Same with Firmware 2006. Just changed the FW-Lines and its back working

PS: Aquasuite 2016-1 was released

**Comment by fariouche** [comment]
I did remember having fixed that, but I think it was only in my brain... ^^
I've already prepared the code to avoid this kind of issue for compatible firmware.
In fact, in the output of the program, you can see the "struct version"
It should be the same for all firmwares. If not, then they changed something and in your case it may be working by chance.

Can you give me the struct version for the latest firmware?
In my case it is 1200...
If it is the same, I will update the code to do the detection based on the structure version and not by using the firmware version.

**Comment by fariouche** [comment]
As soon as the pulrequest is merged, this bug should be fixed (forever ;))

**Comment by barracks510** [comment]
Checkout @fariouche 's changes in `devel` branch.

**Comment by fariouche** [comment]
I believe this issue can be closed too

**Comment by fariouche** [comment]
the 2007 firmware most likely uses a new struct version.
I will have to check this new firmware as soon as I have some time to confirm that
