### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by BOFH90** [Aquaeronix/aquaeronix#16]
Iḿ getting Errors during building and the "werror"-Flag is set.:

`erocli.c: In Funktion »print_system«:
aerocli.c:256:4: Fehler: this »if« clause does not guard... [-Werror=misleading-indentation]
    if (aq_data->cpu_temp[n] != AQ5_FLOAT_UNDEF)
    ^~
aerocli.c:259:5: Anmerkung: ...this statement, but the latter is misleadingly indented as if it is guarded by the »if«
     putchar(' ');
     ^~~~~~~
aerocli.c: In Funktion »print_export«:
aerocli.c:776:3: Fehler: this »if« clause does not guard... [-Werror=misleading-indentation]
   if (aq_data->cpu_temp[n] != AQ5_FLOAT_UNDEF)
   ^~
aerocli.c:778:4: Anmerkung: ...this statement, but the latter is misleadingly indented as if it is guarded by the »if«
    printf("SYS_TEMP_CPU%d_NAME='%s'\n", n+1, libaquaero5_get_name(NAME_CPU, n));
    ^~~~~~
aerocli.c:817:3: Fehler: this »if« clause does not guard... [-Werror=misleading-indentation]
   if (aq_data->flow[n] != AQ5_FLOAT_UNDEF)
   ^~
aerocli.c:819:4: Anmerkung: ...this statement, but the latter is misleadingly indented as if it is guarded by the »if«
    printf("FLOW%d=%.1f\n", n+1, aq_data->flow[n]);
    ^~~~~~
cc1: Alle Warnungen werden als Fehler behandelt
`

**Comment by BOFH90** [comment]
Builds fine with:
make CFLAGS=-Wno-error

**Comment by fariouche** [comment]
I think this issue can be closed, fixed some time ago already

**Comment by BOFH90** [comment]
The problem still exists:
[michael@desktop-mb aerocli]$ make
make  all-recursive
make[1]: Verzeichnis „/home/michael/Downloads/git/aerocli“ wird betreten
Making all in src
make[2]: Verzeichnis „/home/michael/Downloads/git/aerocli/src“ wird betreten
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -Wall -Werror -ansi -std=gnu99 -pedantic -DAQ5_DETECT_FW -g -O2 -MT libaquaero5_la-libaquaero5.lo -MD -MP -MF .deps/libaquaero5_la-libaquaero5.Tpo -c -o libaquaero5_la-libaquaero5.lo `test -f 'libaquaero5.c' || echo './'`libaquaero5.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -Werror -ansi -std=gnu99 -pedantic -DAQ5_DETECT_FW -g -O2 -MT libaquaero5_la-libaquaero5.lo -MD -MP -MF .deps/libaquaero5_la-libaquaero5.Tpo -c libaquaero5.c  -fPIC -DPIC -o .libs/libaquaero5_la-libaquaero5.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -Werror -ansi -std=gnu99 -pedantic -DAQ5_DETECT_FW -g -O2 -MT libaquaero5_la-libaquaero5.lo -MD -MP -MF .deps/libaquaero5_la-libaquaero5.Tpo -c libaquaero5.c -o libaquaero5_la-libaquaero5.o >/dev/null 2>&1
mv -f .deps/libaquaero5_la-libaquaero5.Tpo .deps/libaquaero5_la-libaquaero5.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc -Wall -Werror -ansi -std=gnu99 -pedantic -DAQ5_DETECT_FW -g -O2 -version-info 1:0  -o libaquaero5.la -rpath /usr/local/lib libaquaero5_la-libaquaero5.lo  -lpthread -lpthread 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libaquaero5_la-libaquaero5.o   -lpthread  -g -O2   -Wl,-soname -Wl,libaquaero5.so.1 -o .libs/libaquaero5.so.1.0.0
libtool: link: (cd ".libs" && rm -f "libaquaero5.so.1" && ln -s "libaquaero5.so.1.0.0" "libaquaero5.so.1")
libtool: link: (cd ".libs" && rm -f "libaquaero5.so" && ln -s "libaquaero5.so.1.0.0" "libaquaero5.so")
libtool: link: ar cr .libs/libaquaero5.a  libaquaero5_la-libaquaero5.o
libtool: link: ranlib .libs/libaquaero5.a
libtool: link: ( cd ".libs" && rm -f "libaquaero5.la" && ln -s "../libaquaero5.la" "libaquaero5.la" )
gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -Wall -Werror -ansi -std=gnu99 -pedantic -DAQ5_DETECT_FW -g -O2 -MT aerocli-aerocli.o -MD -MP -MF .deps/aerocli-aerocli.Tpo -c -o aerocli-aerocli.o `test -f 'aerocli.c' || echo './'`aerocli.c
aerocli.c: In Funktion »print_system«:
aerocli.c:257:4: Fehler: diese »if«-Klausel beschützt nicht … [-Werror=misleading-indentation]
    if (aq_data->cpu_temp[n] != AQ5_FLOAT_UNDEF)
    ^~
aerocli.c:260:5: Anmerkung: … diese Anweisung, aber letztere ist verwirrend eingerückt, als wäre sie abhängig von »if«
     putchar(' ');
     ^~~~~~~
aerocli.c: In Funktion »print_export«:
aerocli.c:777:3: Fehler: diese »if«-Klausel beschützt nicht … [-Werror=misleading-indentation]
   if (aq_data->cpu_temp[n] != AQ5_FLOAT_UNDEF)
   ^~
aerocli.c:779:4: Anmerkung: … diese Anweisung, aber letztere ist verwirrend eingerückt, als wäre sie abhängig von »if«
    printf("SYS_TEMP_CPU%d_NAME='%s'\n", n+1, libaquaero5_get_name(NAME_CPU, n));
    ^~~~~~
aerocli.c:818:3: Fehler: diese »if«-Klausel beschützt nicht … [-Werror=misleading-indentation]
   if (aq_data->flow[n] != AQ5_FLOAT_UNDEF)
   ^~
aerocli.c:820:4: Anmerkung: … diese Anweisung, aber letztere ist verwirrend eingerückt, als wäre sie abhängig von »if«
    printf("FLOW%d=%.1f\n", n+1, aq_data->flow[n]);
    ^~~~~~
cc1: Alle Warnungen werden als Fehler behandelt
make[2]: *** [Makefile:498: aerocli-aerocli.o] Fehler 1
make[2]: Verzeichnis „/home/michael/Downloads/git/aerocli/src“ wird verlassen
make[1]: *** [Makefile:390: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/michael/Downloads/git/aerocli“ wird verlassen
make: *** [Makefile:322: all] Fehler 2

**Comment by fariouche** [comment]
oh, I see, my fixes were integrated in the devel branch, not in the stable branch....
EIther you switch to the devel branch or you wait for the owner to re-integrate the fix to the stable branch
