### ISSUE TITLE
Aquaero 5 LT - latest Firmware

### ISSUE THREAD

**Issue by vollschauer** [Aquaeronix/aquaeronix#2]
It builds now but still some strange output with the latest firmware
./aerocli 
WARNING: unsupported firmware version
----------- System -----------
Time:      2014-01-05 01:07:00
Uptime:           00d 00:07:00
CPU Temp:            -99.00 °C
---- Temperature Sensors -----
Sensor  6:            25.52 °C
Sensor 15:            50.00 °C
Sensor 16:            50.00 °C
------------ Fans ------------
Fan  1:   1193rpm @   0% 35 °C
Fan  2:    353rpm @  35% 35 °C
-------- Flow Sensors --------
Flow  1:              3277 l/h
Flow  2:              3277 l/h
Flow  3:              3277 l/h
Flow  4:              3277 l/h
Flow  5:              3277 l/h
Flow  6:              3277 l/h
Flow  7:              3277 l/h
Flow  8:              3277 l/h
Flow  9:              3277 l/h
Flow 10:              3277 l/h
Flow 11:              3277 l/h
Flow 12:              3277 l/h
Flow 13:              6554 l/h
Flow 14:              3277 l/h
------- Liquid Levels --------
Level  1:                 328%
Level  2:                 328%
Level  3:                 328%
Level  4:                 328%

**Comment by BOFH90** [comment]
I only got a good output after i downgraded from 2015-Aquasuite FW to the 2014-Aquasuite FW.
Now with FW 1036 my Output is okay again.

With 20XX FW, i also got a bad output.

**Comment by barracks510** [comment]
I'm working on the latest firmwares right now, and the numbers that don't seem largely off are actually accurate. It would be helpful if you had a windows computer you could use a USB sniffer on. I'd appreciate the extra data. Expect some changes in the master branch sometime soon.

**Comment by fariouche** [comment]
Hello,

I just discovered this fork of aerotools-ng...
I've already made some adjustments to the offsets (at least temps and Fans) for firmware 2002.
I will try to move to aquaeronix since I need the virtual temperature settings.

I will keep you informed soon

**Comment by fariouche** [comment]
Ok, I have a working code with firmware version 2002 (temperatures and fans)
I've also put some enhancements: 
- override a fan value
- autodetect firmware version (no need for the AQ5_FW_TARGET flag anymore)

I will soon install a flow sensor, so I will also set it up properly.

**Comment by BOFH90** [comment]
you are perfect :), i do a update to 2002 as soon the flow sensor works =)
If anyone is interested, i wrote a FW-Downgrade-Guide in German:
-removed-

If the offset is the only fault for the flow sensor, ill do a update to 2002 and report you the offset

**Comment by barracks510** [comment]
Ok. Merged into **devel**. a54ada2b17756a8d338df7e7ee1b159ed492ff9f

@BOFH90 I cannot add your guide to this repo (if that's what you wanted) or distribute it in the RPMs unless you provide the source for your guide (under the terms of the GPL). If you decide to contribute, that documentation would be most appropriate in the `doc` directory in the form of `./doc/fw-downgrade-guide/your-source-files`

**Comment by BOFH90** [comment]
No I dont want to add this to this repo, just for you to test and find the differences between both Firmware Versions. I also don´t know if this works with other Versions than 2002 (to 1036).

If I can test anything for you, just tell me. I also own a Poweradjust 3 and a Aquastream XT to test the Connection to Aquaero via Aquabus

**Comment by fariouche** [comment]
Indeed, I don't know if the aquabus is properly mapped with fw 2002 and above. It should... 
Also, I'm missing the names.  This will be my next step...
By the way, from my investigations, I found that we should not check the fw version, but a specific field called struct version (bytes 5 and 6 of the report), and it seems that there are 3 of them out there...

I hope aquacomputer will help to save us some time

**Comment by barracks510** [comment]
Aquacomputer has generally been difficult to get real information out of. They did suggest looking at the [plugin api](https://github.com/aquacomputer/plugin_sdk/blob/master/DeviceSdk/aquastream_xt/data_layout_aquastream_xt.h) for some information. I'm not sure what changed from Windows into Linux but their bindings simply don't work in Linux, even after convert to hex, but that's something I can look into further.

By the way, I only speak English... _sorry_

**Comment by fariouche** [comment]
Yes, I've studied the structure in structure_version_1200/data_layout_1200.h, and it almost match... almost.
Up to the "temperatures" field it is ok. But the "fans" field is not ok... So something is missing in this structure between "temperatures" and "fans"...

Also, the struct version field is 1200 from my aquaero device with fw 2002.
So I believe that an other struct version 1013 should exist for fw 1036 and above up to 2000.
struct version 1004 is for fw 1020 and above up to 1036... but something is not right.
