### ISSUE TITLE
Aquaeronix Error with FW 1036 (Aquaero 6 Pro)

### ISSUE THREAD

**Issue by BOFH90** [Aquaeronix/aquaeronix#3]
After todays clone and make, I got following error when I try to run aerocli as user or root:

WARNING: unsupported firmware version
failed to get names: Failed to find enough matching report pages! (Bad file descriptor)

On previous Version, i got normal output.

**Comment by barracks510** [comment]
Ok. I'll see what I can do. It may take some time, as I personally don't own an Aquaero 6.

**Comment by fariouche** [comment]
I can reproduce this issue with my aquaero 5 pro...
Even under windows with virtualbox.
BOFH90, do you know the version that used to be working? I would like to do a diff.

**Comment by fariouche** [comment]
I've done a wireshark capture, and I can see that the names are not retrieved the same way...
aquaeronix is doing a set report and is expecting 8 0xC reports...
But it seems that the device only sends 4 reports 0xC, and the host is sent 3 time a set report, waiting then for 4 reports each.
Also, the report name len changed and is now 1102 bytes.

The first sent report  (1102 bytes) starts with [09 01 00 09 40 00 00 00 10] and ends with [12 e7 00 00]
The answer : 4 1102bytes reports.
Second sent report: [09 01 00 09 50 00 00 00 10], ends the same
The answer : 4 1102bytes reports.
Third ans last sent report: [ 09 01 00 09 60 00 00 00 10], same end
Same number of answered reports

All this was captured with fw 2002/2003... 
I suspect that FW 1036 is behaving the same way?

Currently, aquaeronix is sending one report [ 09 01 00 09 C0 00 00 00 10], and the device is responding back 4 reports (but with strange data inside, no names)

I don't know if I will be able to implement the new method without breaking old firmwares compatibility, as I don't have the time to downgrade to 1036.

**Comment by fariouche** [comment]
I almost got the names working.... But it seems random (and I better understand why the code is doing multiple retries). There is something wrong I think.
Wireshark can the the interrupt 100% of the time. So why are we missing some of them?
I still do not understand how the IOCTLs are working here. There must be a way to avoid polling.

**Comment by barracks510** [comment]
Aquacomputer warned us about this... 

I'm not sure what changed. I've been looking at diffs between versions and I cannot pinpoint which one of my patches caused the break with the 1036 firmware. 

I do have a new stock of data that I'm working through on the 20XX firmware. But I will definitely have to refactor to have 10XX and 20XX dual support in the same program.

**Comment by fariouche** [comment]
in fact, my next addon will be to avoid doing fw detection, but instead use the structure version field (that is its purpose)
1200 is the struct version for firmwares >=2000.
For FW 1036, I think it's version 1013... maybe you can confirm this?

When you developed the name parsing, did you use FW 1036?
With FW 20XX, There are 2 problems:
1- usage reports are not anymore retrieved on the same usage id 0xC0, but broken into 3 usage reports, 0x40, 0x50 and 0x60.
2- There is an issue with the linux ioctls. We are missing some interrupts (the answers are sent every 2ms) if we keep the 7ms sleep in the interruptRead function. And doing a 1ms sleep makes thinks almost perfect, but we can still miss one interrupt this way... I tried to use poll, but it does not work with ioctl(), only with read(). I really don't know yet how to wait for an interrupt packet instead of polling.

**Comment by barracks510** [comment]
Yes, name parsing was developed with FW 1036 in mind. FW 20XX had not yet come out. However, I don't believe I or the previous project (no longer in development) used any of the Aquacomputer provided structs when building the software. 

If I remember correctly, hiddev does not natively support waiting for packets. The 7ms sleep was used because a 1ms poll time created erratic output on the device.

**Comment by fariouche** [comment]
understood.
The polling issue you faced, I did not encountered it. Maybe it was solved with fw 2002?

Also, comparing with aquasuite, I've seen that we were sending hid commands to the device when getting the names. 
The HIDIOCGREPORT was the culprit and seems not needed to read the reports/usages.
So, with this ioctl removed, we can poll as fast as we want to catch all the packets using HIDIOCGUSAGES. We'll never spam the aquaero anymore.

**Comment by fariouche** [comment]
I've just got it to work with 100% success, without polling, without using HIDIOCGUSAGES, just by using read().

**Comment by fariouche** [comment]
ok, everything seems to work as expected (at least for fw >= 2000)
Before commiting, I will try to unify the code for fw 2XXX and 1XXX (currently I've split it in two to get the names, but I believe that it will work the same on both fw)
If you have a way to test it with fw 1036, I can commit something tomorrow I hope.

**Comment by BOFH90** [comment]
Hi, just tested it with FW 1036 and got the following Error:

WARNING: unsupported firmware version
failed to get names: Failed to find enough matching report pages! (Bad file descriptor)

**Comment by fariouche** [comment]
unsupported firmware version is strange... I believe that you are using the stable branch which is still not up to date.
For the failed names, it is normal, I just commited the new code a few minutes ago (but haven't changed the code for firmwares below 2000 yet as I cannot test it) 
What I can do is to commit an experimental modification for FW1036, wait for barracks510 to merge it here in the devel branch, and you run it with DEBUG flag and report the result back to me here.

**Comment by BOFH90** [comment]
sorry, yes, I cloned the stable branch.., 
after cloning the devel branch i get the following:
"Unsupported firmware 1036
failed to poll: (null) (Bad file descriptor)"

How do I run it with DEBUG flag ?

**Comment by fariouche** [comment]
I'm preparing something to debug fw 1036. I will let you know as soon as it's ready (tomorrow I hope)

**Comment by fariouche** [comment]
Ok, just got the modification done for testing.
If you can clone my devel branch:
https://github.com/fariouche/aquaeronix.git

It is by default in debug mode.
I've done the modification blindly. 
Execute aerocli -a. So what may happen:
Either of the following points:
- It works ( :) )
- You get an error about fw version 0. (this is a known bug if you execute it the very first time). Just relaunch it.
- It hangs. Ctrl+C and execute it again 2 or 3 times. Give me then the outputs.
- The values are wrong, or they seems good but the names are not correct. You should then have a file named dump_names.bin. Send it to me + the output.

Hope it works the first time.

**Comment by BOFH90** [comment]
It works with 1036 :+1: 
You are my hero :)

But i think I have to upgrade to FW 200X as my board doesnt recognize my aquero every time and aquacomputer told this was fixed with FW2XXX.

**Comment by fariouche** [comment]
ok, good news!
I will then do some cleanup and push the modifications upstream.
If you don't use any low speed aquabus device, then you can migrate to fw 2XXX
